version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: "redis:6.2.6"
    hostname: redis
    expose:
      - "6379"
    env_file:
      - .env